# Generated by Django 4.2.11 on 2024-05-23 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_biblioteca_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectores',
            old_name='correo',
            new_name='observaciones',
        ),
    ]
