# Generated by Django 4.2.11 on 2024-05-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_biblioteca_app', '0002_rename_correo_lectores_observaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectores',
            old_name='nombre',
            new_name='lector',
        ),
    ]
