# Generated by Django 3.2 on 2024-05-30 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_biblioteca_app', '0004_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=200, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('curso', models.CharField(blank=True, max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField()),
                ('devuelto', models.BooleanField(default=False)),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_biblioteca_app.lector')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_biblioteca_app.libro')),
            ],
        ),
        migrations.DeleteModel(
            name='lectores',
        ),
    ]
